### ISSUE TITLE
Curious where this came from, don't seem to be from the [guide](https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-sign-in-with-something-other-than-their-email-address).

### ISSUE THREAD

**Issue by spioupiou** [spioupiou/de-bored#5]
Curious where this came from, don't seem to be from the [guide](https://github.com/heartcombo/devise/wiki/How-To:-Allow-users-to-sign-in-with-something-other-than-their-email-address).

_Originally posted by @carlnoval in https://github.com/spioupiou/de-bored/pull/3#discussion_r804781812_

**Comment by spioupiou** [comment]
This comes from our lecture :) because the guide says:

Next, make sure you can set that field when you create and edit users. When using the [strong parameters](http://guides.rubyonrails.org/action_controller_overview.html#strong-parameters) feature in newer versions of Rails, permit reading of that parameter in the controller with .permit(:username). Or if you’re using an older version of Rails, make the field accessible in your model with attr_accessible :username instead.


So I figured I could just permit nickname and username as we did for prefectures :)

**Comment by carlnoval** [comment]
Oh yes OMG, I completely forgot about this already :( Thanks for the reminder.
