### ISSUE TITLE
Remove email method

### ISSUE THREAD

**Issue by spioupiou** [spioupiou/de-bored#6]
Tried removing this and still was able to create a user and update a nickname, since no longer made the email required I think we should just remove this.

_Originally posted by @carlnoval in https://github.com/spioupiou/de-bored/pull/3#discussion_r804800115_

**Comment by spioupiou** [comment]
I think in that case we should remove email completely, not just allow null emails (right now all users that I create have an empty email but technically they still have an email) let me try to modify the migration

**Comment by spioupiou** [comment]
I deleted that method :) 
I also tried to delete email completely in my migration file (with remove_column etc.) but no use, emails always get created no matter what. I only managed to make them empty strings. I don't think they cause troubles and I would leave it this way to not break devise but please let me know if you find a solution!
![Screen Shot 2022-02-12 at 7 48 46](https://user-images.githubusercontent.com/68413600/153681586-6a96a5fb-c332-4c72-958f-ba6b9521448b.png)

**Comment by carlnoval** [comment]
Did some looking around, could not find any solution as well, however, found [this](https://dev-qa.com/1567801/how-to-completely-remove-email-validation-in-devise). The suggestions was to not use devise if we're not gonna use emails for authentication. But then again I think its fine that we at least managed to make the email into an empty string.
