### ISSUE TITLE
Nicknames don’t have to be unique

### ISSUE THREAD

**Issue by spioupiou** [spioupiou/de-bored#7]
🤔 I don't see any reason why we'd have to make nicknames unique. I think it would be more fun if we leave this as a free for all but only limit to certain characters: upper/lower case alphanumeric and maybe space only. Makes me wonder if we've done some regex validations before.

_Originally posted by @carlnoval in https://github.com/spioupiou/de-bored/pull/3#discussion_r804803339_

**Comment by spioupiou** [comment]
I modified the migration file so that nicknames don't have to be unique :) I think we can add regex later on but let me know if you would prefer doing it now!

**Comment by carlnoval** [comment]
Yeah we can add regex later.
